require("kdev.plugins-setup")
require("kdev.core.options")
require("kdev.core.keymaps")
require("kdev.core.colorscheme")
require("kdev.plugins.comment")
require("kdev.plugins.nvim-tree")
require("kdev.plugins.lualine")
require("kdev.plugins.telescope")
require("kdev.plugins.nvim-cmp")
require("kdev.plugins.lsp.mason")
require("kdev.plugins.lsp.lspsaga")
require("kdev.plugins.lsp.lspconfig")
require("kdev.plugins.lsp.null-ls")
require("kdev.plugins.autopairs")
require("kdev.plugins.treesitter")
require("kdev.plugins.gitsigns")

